-- AlterTable
ALTER TABLE `reports` ADD COLUMN `Cafe` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `Department` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `Gard` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `Library` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `Police` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `Proctor` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `Registrar` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `SuperProctor` BOOLEAN NOT NULL DEFAULT false;
